name: convolutionalists
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pip
  - pytorch=2.5.1
  - torchvision=0.20.1
  # - cudatoolkit
  - jupyter
  - ipykernel
  - pip:
    - transformers==4.46.3
    - ultralytics==8.3.40  # This includes YOLOv11
    - opencv-python
    - matplotlib
    - numpy<2.0.0
    - Pillow
    - requests
    - scipy
    - tqdm
    - pandas
    - seaborn
    - tensorboard
    - roboflow
    - kagglehub