name: convolutionalists
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pip
  - pytorch=1.12.0
  - torchvision=0.13.0
  - cudatoolkit=11.6
  - jupyter
  - ipykernel
  - pip:
    - transformers==4.30.2
    - ultralytics==8.0.0  # This includes YOLOv11
    - opencv-python
    - matplotlib
    - numpy==1.24.0
    - Pillow
    - PyYAML
    - requests
    - scipy
    - tqdm
    - pandas
    - seaborn
    - albumentations
    - pycocotools
    - tensorboard