name: convolutionalists_gpu
channels:
  - defaults
dependencies:
  - python=3.11
  - pip
  - matplotlib
  - numpy
  - tqdm
  - jupyter
  - notebook
  - ipykernel
  - pip:
    - torch==2.0.1
    - torchvision==0.15.2
    - transformers==4.24.0
    - ultralytics==8.3.40
    - opencv-python
    - Pillow
    - requests
    - scipy
    - pandas
    - seaborn
    - tensorboard
    - roboflow
    - kagglehub
    - openimages
    - torchmetrics[detection]